version: '3.8'

services:
  time-service:
    build:
      context: .
      dockerfile: time-service/Dockerfile
    hostname: time-service
    ports:
      - "50052:50052"
    

  greeter-service:
    build:
      context: .
      dockerfile: greeter-service/Dockerfile
    hostname: greeter-service
    ports:
      - "50051:50051"
    depends_on:
      - time-service